### ISSUE TITLE
@hook('before_request') doesn't work

### ISSUE THREAD

**Issue by roessland** [salimane/bottle-mvc#1]
In an ordinary Bottle project, the server prints "whoop!" on every request, using this function:

```
@hook('before_request')
def whoop():
    print "whoop!"
```

But the function does not run when I put it in a file under /controllers in Bottle MVC, for example in `controllers/printer.py` in a newly cloned application.

**Comment by salimane** [comment]
I added the following to bottle-mvc/project/controllers/printer.py

``` python

@app.hook('before_request')
def whoop():
    print "whoop!"

```

and it's printing "whoop!" on the console
Thanks

**Comment by roessland** [comment]
Thank you, using @app.hook instead of @hook worked!
